### PR TITLE
Implement generic FunctionDetour class

### PR DESCRIPTION
**Pull request by dbelz**
Hey Dude,

have done the following things:

- Added a generic class which uses the current implementation as base
- Added more parameter checks
- Changed exceptions which are thrown when something went wrong (Argument, ArgumentNull, InvalidOperationException)
- Renamed some variables
- Created Binding Flags constant in FunctionDetour class
- Added a check for the NoInlining method attribute

If you have any questions feel free to ask :D

### CODE REVIEW

**Comment by Akaion** [comment]
Hi, thanks for the pull request.

I'd like to request some changes before I merge this.

Firstly, checking for no in-lining is a good addition for the target function but it can't be implemented for the source function as this would mean you cannot detour any third party functions that don't have the no in-lining attribute.

Generic detour is a good addition but I would probably put it in the same file as the original detour implementation as an overload.

Not a fan of the variable renaming. Please revert them to what they were.

Wouldn't put that optional parameter in for the function detour. I understand that you put it there as a shortcut but looking at the implementation of using that in code it just makes the code harder to read.

Bit of a nit picky one here but constants with all caps isn't part of the official C# naming conventions and should be PascalCase.

Other than that, thanks for the additions. I will merge them when the above fixes are applied :))

**Comment by dbelz** [comment]
Hey,

have done the things you said. Also have added a bunch of unit tests for the proper exception throwing and so on. 
I haven't moved the generic stuff to the base class because you can't use generics on constructor level. So if we move them to the class we always need to write: new FunctionDetour<Class1, Class2>(methodInfo1, methodInfo2) even if we already have that method info.

What do you think about it?

**Comment by Akaion** [comment]
Looks good.  Thanks for this.

Will do some quick testing when I get back home on Monday and merge then.

**Comment by dbelz** [comment]
Great, thanks! :)

**Comment by Akaion** [comment]
@dbelz Hi dbelz. I'm going to merge this now but will not will not add the changes to the nuget package just yet as I have plans to re-do the architecture of this library in the near future. 

Thanks again for your additions

**Pull request merged**
